name: Endor Labs Scan
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    permissions: 
      security-events: write
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        
      - name: Setup JDK with Maven
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
      
      - name: Build release package
        run: mvn -B clean install
        
        
      - name: Endor Labs Workflow Dispatch
        uses: endorlabs/github-action@main
        with:
          namespace: "matt-demo"
          api: "https://api.endorlabs.com"
          scan_summary_output_type: "table"
          enable_pr_comments: true
          enable_github_action_token: true
          github_token: ${{ secrets.GH_TOKEN }} 
          tags: "actor = ${{ github.actor }},run-id = ${{ github.run_id }},event name = ${{ github.event_name }},workflow = ${{ github.workflow }}"
          sarif_file: endor-labs.sarif
      
      - name: Upload SARIF to github
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: endor-labs.sarif
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: endorlabs-java-webapp-demo
          path: |
            target/endor-java-webapp-demo.jar
        
      
